analysis/urls.py
from django.conf.urls import url 
from analysis import views
from django.urls import path 
from django.conf.urls.static import static

app_name = 'analysis'

urlpatterns=[
    path('',views.HomePageView.as_view(), name='home'),
    # path('getnum/',views.Api.getNums, name='get-num'),
    # path('getavg/',views.Api.getAvg, name='get-avg'),
    # path('getgraph/',views.Api.getGraph, name='get-graph'),
    path('getdata/',views.Api.getData, name='get-data'),
    path('get-unigrams-graph/',views.Api.getUnigramsGraph, name='get-unigrams-graph'),
    path('get-bigrams-graph/',views.Api.getBigramsGraph, name='get-bigrams-graph'),
    path('get-trigrams-graph/',views.Api.getTrigramsGraph, name='get-trigrams-graph'),
    # path('chart/',views.HomeView.as_view(), name='home-view'),
    # path('chart-api/',views.ChartData.as_view(), name='chart-api'),
    # path('plotly-chart/',views.PlotlyChartView.as_view(), name='plotly-chart'),

]

project1/urls.py
from pivottable.views import home
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from welcome import views
# from analysis import views
from project1.settings import DEBUG, STATIC_URL, STATIC_DIR, MEDIA_URL,MEDIA_ROOT
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$',views.index,name='index'),
    url(r'^special/',views.special,name='special'),
    url(r'^welcome/',include('welcome.urls')),
    url(r'^logout/$',views.user_logout, name='logout'),
    url(r'^pivottable/',include('pivottable.urls')),
    url(r'^analysis/',include('analysis.urls'))

]

if DEBUG:
    urlpatterns += static(MEDIA_URL, document_root = MEDIA_ROOT)

welcome/urls.py
from django.conf.urls import url
from welcome import views

# SET THE NAMESPACE!
app_name = 'welcome'

# Be careful setting the name to just /login 
# use userlogin instead!

urlpatterns=[
    url(r'^register/$',views.register,name='register'),
    url(r'^user_login/$',views.user_login,name='user_login')
]

analysis/models.py
from django.db import models

# Create your models here.

analysis/views.py
from django.shortcuts import render
from django.http import HttpResponse
from project1.settings import MEDIA_URL,MEDIA_ROOT
from django.conf.urls.static import static
from django.views.generic import TemplateView, View 

import numpy as np
import pandas as pd
import matplotlib as pl
pl.use('Agg')
import matplotlib.pyplot as plt
import seaborn as sb

# Data loading
pickle_path = MEDIA_ROOT+"/Data/df_hotstock_analysis.pkl"
df = pd.read_pickle(pickle_path)

df.rename(columns={
'Rank'           : 'Popularity Rank'     ,
'Stock_Name'     : 'Stock Name'          ,
'Company'        : 'Company Name'        ,
'Score'          : 'Trends Score'        ,
'total_comments' : 'Total Comments'      ,
'unique_user'    : 'Unique User'         ,
'min_comments_dt': 'Oldest Comment Date' ,
'max_comments_dt': 'Latest Comment Date' ,
'dt_difference'  : 'Time Differences'    ,
'avg_negative'   : 'Negative Sentiment'  ,
'avg_neutral'    : 'Neutral Sentiment'   ,
'avg_positive'   : 'Positive Sentiment'  ,
'avg_compound'   : 'Overall Sentiment'   ,
'top_n1'         : 'Top Unigrams Keyword',
'top_n2'         : 'Top Bigrams Keyword' ,
'top_n3'         : 'Top Trigrams Keyword',}, inplace=True)

class HomePageView(TemplateView):
    def get(self,request,**kwargs):
        return render(request, 'analysis/index.html', context=None)

class Api(TemplateView):
    # Create your views here.
    def getData(request):

        return HttpResponse(df.to_html(classes='table table-bordered'))

    def getUnigramsGraph(request):

        sn=request.GET.get("val","")
        stock_mask = df['Stock Name'] == sn

        if stock_mask.any():
            print("im here")
            topn= df[stock_mask]['Top Unigrams Keyword'].values[0]

            top_df= pd.DataFrame(topn)
            top_df.columns=["Word","Freq"]
            sb.set(rc={'figure.figsize':(13,8)})
            graph = sb.barplot(x="Word",y="Freq", data=top_df)
            graph.set_xticklabels(graph.get_xticklabels(),rotation=30)
            response = HttpResponse(content_type="image/jpeg")
            graph.figure.savefig(response, format="png")
            return response

        else:
            return HttpResponse("none")

    def getBigramsGraph(request):

        sn=request.GET.get("val","")
        stock_mask = df['Stock Name'] == sn

        if stock_mask.any():
            print("im here")
            topn= df[stock_mask]['Top Bigrams Keyword'].values[0]

            top_df= pd.DataFrame(topn)
            top_df.columns=["Word","Freq"]
            sb.set(rc={'figure.figsize':(13,8)})
            graph = sb.barplot(x="Word",y="Freq", data=top_df)
            graph.set_xticklabels(graph.get_xticklabels(),rotation=30)
            response = HttpResponse(content_type="image/jpeg")
            graph.figure.savefig(response, format="png")
            return response

        else:
            return HttpResponse("none")

    def getTrigramsGraph(request):

        sn=request.GET.get("val","")
        stock_mask = df['Stock Name'] == sn

        if stock_mask.any():
            print("im here")
            topn= df[stock_mask]['Top Trigrams Keyword'].values[0]

            top_df= pd.DataFrame(topn)
            top_df.columns=["Word","Freq"]
            sb.set(rc={'figure.figsize':(13,8)})
            graph = sb.barplot(x="Word",y="Freq", data=top_df)
            graph.set_xticklabels(graph.get_xticklabels(),rotation=30)
            response = HttpResponse(content_type="image/jpeg")
            graph.figure.savefig(response, format="png")
            return response

        else:
            return HttpResponse("none")
        

templates/analysis/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <!-- Latest compiled and minified CSS -->
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script></head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
{# Django Home Link / Admin Link / Register Link#}
          <li><a class="navbar-brand" href="#">DJANGO</a></li>
          <li><a class="navbar-link" href="#">Admin</a></li>
          <li><a class="navbar-link" href="#">Register</a></li>     
          {# Some logic on what to display for last item#}
          {% if user.is_authenticated %}
            <li><a href="{% url 'logout' %}">Logout</a></li>
          {% else %}
            <li><a class="navbar-link" href="#">Login</a></li>
          {% endif %}
</ul>
      </div>
    </nav>
    {% block body_block %}
    {% endblock %}
  </body>
</html>

templates/analysis/charts.html
{% extends "analysis/base.html" %}
{% block body_block %}
<div class="container-fluid">
    <center class="row">
        <h2>Our Implementation of <b>Chart.js</b> in Django</h2>
    </center>
    <hr>
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-6">
            <canvas id="myChartLine"></canvas>
        </div>
        <div class="col-md-3"></div>
    </div>
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-6">
            <canvas id="myChartBar"></canvas>
        </div>
        <div class="col-md-3"></div>
    </div>
</div>
 <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script> 
<script>
    // Make API calls
    $.ajax({
        method: "GET",
        url: "{% url 'analysis:chart-api' %}",
        success: function(data){
            drawLineGraph(data,'myChartLine');
            drawBarGraph(data,'myChartBar');
        },
        error: function(err){
            console.log(err);
        }
    })

    function drawLineGraph(data, id) { 
      var labels = data.labels; 
      var chartLabel = data.chartLabel; 
      var chartdata = data.chartdata; 
      var ctx = document.getElementById(id).getContext('2d'); 
      var chart = new Chart(ctx, { 
        // The type of chart we want to create 
        type: 'line', 
  
        // The data for our dataset 
        data: { 
          labels: labels, 
          datasets: [{ 
            label: chartLabel, 
            backgroundColor: 'rgb(255, 100, 200)', 
            borderColor: 'rgb(55, 99, 132)', 
            data: chartdata, 
          }] 
        }, 
  
        // Configuration options go here 
        options: { 
          scales: { 
            xAxes: [{ 
              display: true 
            }], 
            yAxes: [{ 
              ticks: { 
                beginAtZero: true 
              } 
            }] 
          } 
        } 
  
      }); 
    } 
  
    function drawBarGraph(data, id) { 
      var labels = data.labels; 
      var chartLabel = data.chartLabel; 
      var chartdata = data.chartdata; 
      var ctx = document.getElementById(id).getContext('2d'); 
      var myChart = new Chart(ctx, { 
        type: 'bar', 
        data: { 
          labels: labels, 
          datasets: [{ 
            label: chartLabel, 
            data: chartdata, 
            backgroundColor: [ 
              'rgba(255, 99, 132, 0.2)', 
              'rgba(54, 162, 235, 0.2)', 
              'rgba(255, 206, 86, 0.2)', 
              'rgba(75, 192, 192, 0.2)', 
              'rgba(153, 102, 255, 0.2)', 
              'rgba(255, 159, 64, 0.2)' 
            ], 
            borderColor: [ 
              'rgba(255, 99, 132, 1)', 
              'rgba(54, 162, 235, 1)', 
              'rgba(255, 206, 86, 1)', 
              'rgba(75, 192, 192, 1)', 
              'rgba(153, 102, 255, 1)', 
              'rgba(255, 159, 64, 1)' 
            ], 
            borderWidth: 1 
          }] 
        }, 
        options: { 
          scales: { 
            yAxes: [{ 
              ticks: { 
                beginAtZero: true 
              } 
            }] 
          } 
        } 
      }); 
    }
</script>
{% endblock %}

templates/analysis/index.html
{% extends "analysis/base.html" %}
{% block body_block %}
<div style="text-align:center">
  <h1>
    Welcome to Stock NLP &amp; Sentimental Analysis!
  </h1>
    <div class="container-fluid">
        <div class="row">
             <b>* Note 1:</b> 
             Stock trends are derived from a number of activities related to the stock, each given a weightage and score. The activities contributing to stock scores include: 
             <ul>
                <li>Searches on a stock</li>
                <li>News &amp; blog posts covering a stock</li>
                <li>Price target for a stock</li>
                <li>Announcement on a stock</li>
                <li>Stock entitlement (bonus, dividend, split, consolidation)</li>
            </ul>
            <br>
            <b>* Note 2:</b> 
            The scores are normalised to have maximum score of 1000. Stock with the highest score has the most activities in the past 2 days.
            <br>
            Click below button to view NLP &amp; Sentimental Analysis results
            <br><br>
        </div>

        <div class="row">
            <div class="col-3">
                <button onclick="getPandas()">TOP 30 HOT STOCK</button>
            </div>

            <div id="pandas" class="col-9">
            </div>
        <div>

        <br><br><br><br><br><br><br><br>

        <label>Enter Stock Name:</label>
        <input id="stock_name" type="text" placeholder="GENM, TOPGLOV, AIRASIA...">
                {% comment %} <label>Choose Keywords Models:</label>
                <select name="top_n" id="top_n">
                    <option value="n1">Unigrams</option>
                    <option value="n2">Bigrams</option>
                    <option value="n3">Trigrams</option>
                </select> {% endcomment %}
        <br><br>

        <div class="row">
            <div class="col-3">
                <button onclick="getUnigrams()">Visualize Top Unigrams Keywords</button>
            </div>

            <div class="col-9">
                <img id="unigrams">
            </div>
        <div>

        <br><br><br><br>

        <div class="row">
            <div class="col-3">
                <button onclick="getBigrams()">Visualize Top Bigrams Keywords</button>
            </div>

            <div class="col-9">
                <img id="bigrams">
            </div>
            <br><br><br><br>
        <div>

        <br><br><br><br>
        
        <div class="row">
            <div class="col-3">
                <button onclick="getTrigrams()">Visualize Top Trigrams Keywords</button>
            </div>

            <div class="col-9">
                <img id="trigrams">
            </div>
            <br><br><br><br>
        <div>

    </div>
</div>
<script>
    // Make API calls
    
    function getPandas() {
		fetch('{% url 'analysis:get-data' %}')
		.then(res => res.text())
		.then(data => document.getElementById('pandas').innerHTML = data)
	}

    function getUnigrams() {
        var val_list = document.getElementById('stock_name').value;
		fetch('{% url 'analysis:get-unigrams-graph' %}'+"?val="+val_list)
		.then(res => res.blob())
		.then(data => {
            let imgURL = URL.createObjectURL(data)
            document.getElementById('unigrams').src = imgURL
        })
	}

    function getBigrams() {
        var val_list = document.getElementById('stock_name').value;
		fetch('{% url 'analysis:get-bigrams-graph' %}'+"?val="+val_list)
		.then(res => res.blob())
		.then(data => {
            let imgURL = URL.createObjectURL(data)
            document.getElementById('bigrams').src = imgURL
        })
	}

    function getTrigrams() {
        var val_list = document.getElementById('stock_name').value;
		fetch('{% url 'analysis:get-trigrams-graph' %}'+"?val="+val_list)
		.then(res => res.blob())
		.then(data => {
            let imgURL = URL.createObjectURL(data)
            document.getElementById('trigrams').src = imgURL
        })
	}
    
</script>
{% endblock %}

templates/analysis/plotly.html
{% extends "analysis/base.html" %}
{% block body_block %}
<div class="container-fluid">
    <center class="row">
        <h2>Our Implementation of <b>Plot.ly</b> in Django</h2>
    </center>
    <hr>
    {% autoescape off %}
    {{ plot_div }}
    {% endautoescape %}
</div>
{% endblock %}

templates/analysis/table.html
{% extends "analysis/base.html" %}
{% block body_block %}
<div class="container-fluid">
    <center class="row">
        <h2>Our Implementation of Django Tables</h2>
    </center>
    <hr>
    {% load django_tables2 %}
    {% render_table table %}
</div>
{% endblock %}